import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
    >
      <body className="bg-sefaz-light text-sefaz-gray font-sans antialiased min-h-screen flex flex-col">
        {/* HEADER SUPERIOR */}
        <header className="bg-sefaz-green text-sefaz-light pt-6 pb-0 px-8 shadow-md">
          <div className="max-w-7xl mx-auto flex justify-between items-start mb-6">
            <div className="flex items-center gap-4">
              <div className="bg-maceio-amber text-white font-bold text-xl w-12 h-12 flex items-center justify-center rounded-md">
                SM
              </div>
              <div>
                <h1 className="text-xl font-bold text-white tracking-wide">Sefaz Maceió</h1>
                <p className="text-sm text-green-200/80">Painel de Despesas Públicas · Capitais Brasileiras</p>
              </div>
            </div>
            
            <div className="flex gap-3 text-xs font-semibold">
              <span className="border border-green-700/50 bg-sefaz-green/50 text-green-100 px-3 py-1.5 rounded-full">26 capitais</span>
              <span className="border border-green-700/50 bg-sefaz-green/50 text-green-100 px-3 py-1.5 rounded-full">2020 – 2025</span>
            </div>
          </div>

          <nav className="max-w-7xl mx-auto flex gap-8 text-sm font-medium">
            <span className="pb-3 border-b-2 border-maceio-amber text-white cursor-pointer">Visão Geral</span>
            <span className="pb-3 border-b-2 border-transparent hover:text-white cursor-pointer transition-colors">Raio-X de Maceió</span>
            <span className="pb-3 border-b-2 border-transparent hover:text-white cursor-pointer transition-colors">Comparador de Capitais</span>
          </nav>
        </header>

        
        <main className="flex-1 w-full max-w-7xl mx-auto p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
