import type { Metadata } from "next";
import "./globals.css";
import { Inter, Merriweather } from "next/font/google";
import Nav from "@/componentes/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${merriweather.variable}`}
    >
      <body className="bg-sefaz-light text-sefaz-gray font-sans antialiased min-h-screen flex flex-col">
        {/* HEADER SUPERIOR */}
        <header className="bg-sefaz-green text-sefaz-light pt-6 pb-0 px-8 shadow-md">
          <div className="max-w-7xl mx-auto flex justify-between items-start mb-6">
            <div className="flex items-center gap-4">
              <div className="bg-maceio-amber text-white font-bold text-xl w-12 h-12 flex items-center justify-center rounded-md">
                SM
              </div>
              <div>
                <h1 className="text-xl font-bold text-white tracking-wide">
                  Sefaz Maceió
                </h1>
                <p className="text-sm text-green-200/80">
                  Painel de Despesas Públicas · Capitais Brasileiras
                </p>
              </div>
            </div>

            <div className="flex gap-3 text-xs font-semibold">
              <span className="border border-green-700/50 bg-sefaz-green/50 text-green-100 px-3 py-1.5 rounded-full">
                26 capitais
              </span>
              <span className="border border-green-700/50 bg-sefaz-green/50 text-green-100 px-3 py-1.5 rounded-full">
                2020 – 2025
              </span>
            </div>
          </div>

          <Nav />
        </header>

        {/* FAIXA DE ORIGEM DOS DADOS */}
        <div className="bg-sefaz-light border-b border-black/5 px-8 py-2.5">
          <p className="max-w-7xl mx-auto text-xs text-sefaz-gray flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-maceio-amber inline-block" />
            Dados oficiais · Siconfi/FINBRA 2020–2025 · execução orçamentária
            declarada pelas capitais.
          </p>
        </div>

        <main className="flex-1 w-full max-w-7xl mx-auto p-8">{children}</main>
      </body>
    </html>
  );
}
